[package]
name = "flac-lame-frontend"
version = "2.0.0"
authors = ["Rodrigo Cesar de Freitas Dias <rcesar@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1
#panic = "abort"

[dependencies]
winsafe = { path = "../winsafe" }
